name: main

on:
  workflow_dispatch:

#  schedule:
#    - cron: "0 0 * * *"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: see
        run: |
              git config --local user.email "63339210+rprx@users.noreply.github.com"
              git config --local user.name "RPRX"
              git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
              date '+%Y年%m月%d日：没有' >> ./README.md
              echo >> ./README.md
              echo $i > ./begin
              git add ./README.md
              git add ./begin
              git commit  -m "悲"
              git pull --rebase
              git push
